---
title: "STA 9750 Submission Material"
---
## A Portfolio of Data Analysis Projects from Fall 2026

### About Me
Hello readers! My name is Khushi Gandhi and I am a graduate student studying Statistics at Baruch College. This website will serve as a portfolio for the projects I will complete throughout the Fall 2026 semester for STA 9750.

In modern-day business, reliable data drives strategic planning and informed decision making. This is what encouraged me to pursue an education in Statistics and Mathematics. I received my B.B.A in Statistics and Quantitative Modeling from Baruch College in June 2026. I immediately transitioned to graduate school where I am currently pursuing a Master of Science.

Mathematics is the natural language or our universe and has infinite storytelling potential. That is why I aspire to become a data analyst, preferably through some government role. A career of this nature would perfectly balance my passion for using numbers and doing work that will create meaningful change.


### Skills
- ***Programming and Tools***: R, Microsoft Excel (VBA, Macros), Microsoft PowerPoint, Microsoft Access, Python
- ***Statistical Methods***: Multiple Linear Regression, Logistic Regression, Time-Series Forecasting, Machine Learning


### Past Technical Projects
***Structural Predictors of Chronic Absenteeism in NYC Public Schools***\
*Contributor* | [GitHub](https://github.com/soniatyburczy/absenteeism-structural-predictors)

- Cleaned and standardized various datasets across 7,600+ records and 50 variables using R to evaluate institutional drivers of chronic absenteeism in NYC public schools.
- Evaluated multiple linear regression models, translating statistical findings into a strategic written summary highlighting high-impact predictive factors.

***Linking Lifestyle Traits to an Increased Risk of Diabetes***\
*Contributor*\

- Modeled a CDC health survey dataset in R with 200k+ records using logistic regression to evaluate key demographic and lifestyle risk factors.
-	Designed data visualizations and delivered a structured diagnostic report, translating odds ratios and confidence intervals into clear takeaways.

### Something less relevant...
> "There is no happiness for him who does not travel ... Therefore, wander!”
> 
> ― Aitareya Brahmanan, *The Rigveda*

Aside from being passionate about working with data, I also love to travel. Learning about ancient history, various cultures and unique places is exciting and a form of education in itself. That is why during my undergraduate studies, I studied abroad. 

Though my study abroad experience only lasted three weeks, those three weeks offered unforgettable experiences. I had the wonderful opportunity to spend January 2026 in Kyoto, Japan taking a class on Japanese Manga and Art.

***Thinking about visiting someday?*** Here is a map to one of my favorite places I visited in my time there.
```{r}
#| echo: false
#| message: false
#| warning: false

if(!require("leaflet")){
    options(repos=c(CRAN="https://cloud.r-project.org"))
    install.packages("leaflet")
    stopifnot(require("leaflet"))
}

fuji_longitude <- +138.765918
fuji_latitude  <- +35.512724

leaflet() |>
  addTiles() |>
  setView(fuji_longitude, fuji_latitude, zoom=17) |>
  addPopups(fuji_longitude, fuji_latitude, 
            "Mount Fuji over Lake Kawaguchiko!")
```